Page/logincard
SouJunior/vagas-frontend pull request #58
Opened 2022-10-27 17:55 UTC by CarlosJunioor

LoginCard feito, está com alguns bugs referentes a tela, mas o importante que foi o card está feito.

Deixei essas váriaveis para serem armazenadas o e-mail e password.
`
const [email, setEmail] = useState("");
const [password, setPassword] = useState("");
`

- [ ] Deixei espaço para armazenar o e-mail e password.

Tenho algumas dúvidas, mas continuo nos estudos para fazer a ligação da API com a o LoginCard.

2022-10-28 13:27 UTC, allbertuu requested changes
- Adicionado legibilidade ao código
- Apontado erros que podem acontecer
- Apontado correções que precisam ser feitas

2022-10-28 13:27 UTC, allbertuu commented on src/components/Card/Card.tsx
> +
não precisa desse espaço na primeira linha de código em um escopo de função
```suggestion
```

2022-10-28 13:27 UTC, allbertuu commented on src/components/Card/Card.tsx
> +        console.log(email,password)
- remover `console.log`. 
esse código é usado para debug na sua máquina, mas não pode estar no código principal. lembre sempre de retirá-lo.
```suggestion
```

2022-10-28 13:27 UTC, allbertuu commented on src/components/Card/Card.tsx
> +
remover espaço desnecessário
```suggestion
```

2022-10-28 13:27 UTC, allbertuu commented on src/components/Card/Card.tsx
> +                  <span className="absolute inset-y-[20%] right-[2%] z-10 h-full leading-snuf font-normal">
o correto é `leading-snug`. ver https://tailwindcss.com/docs/line-height
```suggestion
                  <span className="absolute inset-y-[20%] right-[2%] z-10 h-full leading-snug font-normal">
```

2022-10-28 13:27 UTC, allbertuu commented on src/components/Card/Card.tsx
> +    <>
não precisa do fragment (<></>) se o retorno da função é somente um children

2022-10-28 13:27 UTC, allbertuu commented on src/components/Card/Card.tsx
> +    <form>
Porquê há outro `form` em torno de todo o código? Só é necessário em volta de elementos de formulário, como você fez lá embaixo (input, textareas etc).
Considere tirá-lo.

2022-10-28 13:27 UTC, allbertuu commented on src/components/Card/Card.tsx
> +                <button className="w-full h-12 rounded mb-5 text-white bg-blue-600" onClick={login} id='submit-button'>
```suggestion
                <button type="submit" className="w-full h-12 rounded mb-5 text-white bg-blue-600" id='submit-button'>
```

2022-10-28 13:27 UTC, allbertuu commented on src/components/Card/Card.tsx
> +            <form>
```suggestion
            <form id="login-form" onSubmit={(e) => handleFormOnSubmit(e)}>
```

2022-10-28 13:27 UTC, allbertuu commented on src/components/Card/Card.tsx
> +    function login(e) {
lembre de nomear suas funções com o máximo de legibilidade - clean code
```suggestion
    function handleFormOnSubmit(e) {
```

2022-10-28 13:27 UTC, allbertuu commented on src/pages/Login.tsx
> +      <Card />
colocar o Card em volta de uma seção. note a estrutura do código.
```suggestion
      <section>
          <Card />
      </section>
```

2022-10-28 13:27 UTC, allbertuu commented on src/components/Card/Card.tsx
> +              <input
esse input de checkbox vai dentro da label logo ali embaixo. parecido com essa imagem, só que o componente Checkbox.Root sendo o input que citei. Assim o checkbox funciona como esperado.
![image](https://user-images.githubusercontent.com/89992304/198607655-ea7a76c7-08d3-4b4e-b602-735cbe2d945f.png)

2022-10-30 01:58 UTC, allbertuu commented
Fiz algumas correções por conta própria para avançar na conclusão da task

2022-10-31 19:00 UTC, SilviaLTeixeira commented
@allbertuu pra esse componente voce quer que todo mundo faça revisao ou voce esta esperando o mentor fazer uma revisao mais detalhada? Qualquer coisa posso revisar tambem o que precisar

2022-10-31 19:48 UTC, allbertuu commented
> @allbertuu pra esse componente voce quer que todo mundo faça revisao ou voce esta esperando o mentor fazer uma revisao mais detalhada? Qualquer coisa posso revisar tambem o que precisar

Uma revisão por sua parte seria de grande ajuda. Nem todos estão disponiveis, qualquer ajuda é bem vinda para finalizar essa task importantissima para concluir a Tela de Login.

2022-10-31 21:01 UTC, SilviaLTeixeira reviewed
Nao tenho nada mais a adicionar alem do que o @allbertuu pontuou

2022-11-29 17:00 UTC, FilipeLeoni approved these changes

2022-11-29 18:17 UTC, allbertuu commented
Esta task será continuada pelo @igords-goncalves em outro PR.

2022-11-29 18:17 UTC, closed without merging