Config axios api
SouJunior/vagas-frontend pull request #72
Opened 2022-11-18 18:34 UTC by SilviaLTeixeira

Instalei o axios nas dependencias do projeto , criei uma pasta services para fazer a parte de serviços do front end e coloquei dentro dela o arquivo api.tsx que tem as configuraçoes iniciais do axios

2022-11-19 14:02 UTC, allbertuu approved these changes
LGTM ✅
> Muito bom

2022-11-19 14:05 UTC, allbertuu requested changes
Renomear o arquivo de `.tsx` para `.ts`, pois o código é somente TS, sem React JSX (componente).

2022-11-21 00:58 UTC, igords-goncalves commented
> Renomear o arquivo de `.tsx` para `.ts`, pois o código é somente TS, sem React JSX (componente).

Creio que também seria interessante colocar a `baseURL` dentro de um arquivo **.env**

2022-11-23 18:17 UTC, allbertuu approved these changes
Corrigido alterações.

2022-11-23 18:18 UTC, merged