Created component LoginCard
SouJunior/vagas-frontend pull request #77
Opened 2022-11-30 17:33 UTC by igords-goncalves

- Criado uma pasta específica dentro da pasta **components** para o componente `LoginCard`.
- Criado o componente `LoginCard` já com código legado de outro Pull Request https://github.com/SouJunior/vagas-frontend/pull/58
- Referenciado `LoginCard` em componente `Login`.

2022-12-02 01:59 UTC, allbertuu commented
Recomendo dentro da pasta `LoginCard`, criar um `index.tsx`, e evitar repetição de palavras (que gera má legibilidade) na importação e organização do elemento.

2022-12-02 02:18 UTC, igords-goncalves commented
> Recomendo dentro da pasta `LoginCard`, criar um `index.tsx`, e evitar repetição de palavras (que gera má legibilidade) na importação e organização do elemento.

Sim, entendi o padrão, considere feito.

2022-12-14 19:50 UTC, allbertuu requested changes
Apenas algumas observações para correção. No geral, muito bom.

2022-12-14 19:50 UTC, allbertuu commented on src/components/Card/index.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */ //remover essa linha depois
conforme o comentário posto, remover esta linha
```suggestion
```

2022-12-14 19:50 UTC, allbertuu commented on src/components/Card/index.tsx
> +import React, { useState } from 'react';
na versão atual do React neste projeto, não é preciso importar o React - [confira](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)

```suggestion
import { useState } from 'react';
```

2022-12-14 19:50 UTC, allbertuu commented on src/components/Card/index.tsx
> +                        <a href="https://google.com">Criar conta</a>
qual o motivo dessa URL estar presente aqui?

2022-12-14 19:50 UTC, allbertuu commented on src/pages/Login.tsx
>  import React from 'react';
mesma coisa de antes
```suggestion
```

2022-12-14 19:50 UTC, allbertuu commented on src/pages/Login.tsx
> +import Card from '../components/Card/index';
tudo bem ser assim, mas poderia ser somente `../components/Card`

2022-12-16 23:43 UTC, allbertuu approved these changes
Aprovado por mim.

2022-12-19 15:33 UTC, merged