Barra de ferramentas da descrição criada.
SouJunior/vagas-frontend pull request #83
Opened 2023-01-10 17:38 UTC by FilipeLeoni

![Captura de tela 2023-01-10 143724](https://user-images.githubusercontent.com/100960828/211622898-dffa38d4-d4cc-4ea5-b25d-4567ef7a823a.png)
![Captura de tela 2023-01-10 143749](https://user-images.githubusercontent.com/100960828/211622902-5de0ed15-c4c7-4d83-be0d-84dbc9adbb49.png)

2023-01-11 23:40 UTC, allbertuu commented on src/components/Tiptap.tsx
> +                            editor.chain().focus().toggleStrike().run();
notei esse mesmo bloco de código (esse button todo), com apenas 1 ou 2 mudanças entre cada uma delas.

que tal refatorar isso em um componente? `ToggleOption`, por exemplo

2023-01-19 00:06 UTC, allbertuu requested changes

2023-01-19 00:06 UTC, allbertuu commented on package.json
> -    "@types/node": "^16.7.13",
Acredito que essa exclusão foi acidental. Esse pacote do Node com definições de tipo para o mesmo é muito importante.

De resto, parabéns!!!

2023-01-19 10:17 UTC, limaricardo requested changes

2023-01-19 10:17 UTC, limaricardo commented on src/components/ToggleOption.tsx
> +const ToggleOptions = ({ editor, children, type, toggleType }: any) => {
Fala Filipe, como se trata de um componente único o legal seria você renomear para `ToggleOption`, no singular.

2023-01-19 10:21 UTC, limaricardo requested changes

2023-01-19 10:21 UTC, limaricardo commented on src/components/Tiptap.tsx
> +    const ToggleFunctions: Options = {
Essa parte poderia alterar os nomes. Seguindo a convenção de clean code para nomeação de constantes 
```suggestion
    const TOGGLE_OPTIONS = ['bold', 'italic', 'strike', 'bulletlist'];
    const TOGGLE_FUNCTIONS: Options = {
```

2023-01-19 11:30 UTC, FilipeLeoni commented on package.json
> -    "@types/node": "^16.7.13",
Realmente foi acidental, mas acredito que agora está resolvido

2023-01-24 12:38 UTC, limaricardo approved these changes

2023-01-24 12:39 UTC, limaricardo approved these changes

2023-01-24 12:43 UTC, limaricardo approved these changes

2023-01-24 23:50 UTC, allbertuu approved these changes
Aprovado! 🆗️

2023-01-25 00:36 UTC, merged